### ISSUE TITLE
Lab #5 

### ISSUE THREAD

**Issue by jumphrey77** [MicrosoftLearning/20537-Configuring-and-Operating-a-Hybrid-Cloud-with-Microsoft-Azure-Stack#8]
Lab 5 has instructions in Exercise #2, Task 2 asks the student to create a new credential in Powershell based the user AzureStack\ASUserX.  This account is not created until Lab #6.  Is this a typo? Are we supposed to use AzureStack\AzureStackAdminX  or are the instructions in error?

**Comment by JustinKimber** [comment]
You are right, this is a bug. Please use AzureStack\AzureStackAdminX instead for this task. Also select the Virtual MachinesX subscription in Step 12 of the LAK instead of the ASUserX subscription. I will update the lab accordingly. Thanks.

**Comment by JustinKimber** [comment]
Updated the Lab to fix thisl
